### ISSUE TITLE
使用发现了一些bug和提一些建议

### ISSUE THREAD

**Issue by nsnans** [ponysb/TagPlanet#1]
## bug
- 高度问题
![image](https://github.com/user-attachments/assets/5af82720-c689-4d27-96d6-f01d2acdf457)
- 间距问题
![image](https://github.com/user-attachments/assets/5ce96465-85b3-4094-8a89-599d359b0b20)
- 获取标签页出现了一个不存在的
![image](https://github.com/user-attachments/assets/77c15248-ec84-4cd2-99e0-a68b9349e95c)

## 建议
- 出现标签管理页面的方式调整
>改为点击后出现，因为新建标签页会与`Infinity拓展`冲突，导致二者只能存一个
![image](https://github.com/user-attachments/assets/b88bf259-c14f-4ca1-b6d1-c809f95cdf76)
- 书签顺序调整
>其他标签栏放下面，书签栏放上面
![image](https://github.com/user-attachments/assets/d990e8a3-2dc1-4d04-b44c-3030923b7eaa)
- 区域宽度调整
![image](https://github.com/user-attachments/assets/a6bdbcec-b97b-45d7-97f4-a63cccba672c)

**Comment by ponysb** [comment]
非常好的建议
1.后续会优化高度适配以及排除标签星球本身Tab的问题
2.浏览器规定新建标签页只允许有一个所以与其他起始页冲突问题比较难解决，暂时我也没想到好的方案，后续想到会考虑调整
3.两行之间的bug问题会在下一期修复

**Comment by nsnans** [comment]
>浏览器规定新建标签页只允许有一个所以与其他起始页冲突问题比较难解决，暂时我也没想到好的方案，后续想到会考虑调整

@ponysb 可以考虑下我的建议，改为点击后出现。

还有下面`书签顺序调整`，其他书签就是不重要的书签，应该放下面，这个可以考虑改下

**Comment by ponysb** [comment]
书签顺序是根据浏览器自带的收藏功能来的，在标签页里调整比较麻烦，不太打算做这块的功能
